# docker-compose for Jenkins and Jenkins agent
version: '3.8'

services:

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    privileged: true
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  build-agent:
    build:
      context: .
      dockerfile: build-agent.Dockerfile
    privileged: true
    user: root
    container_name: build-agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${AGENT_PUBKEY}
