cors:
  allowed-origins: "http://localhost:4200"

spring:
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "genemis"
      username: "genemis"
      password: "genemispswd"

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "/api/healthcheck"