cors:
  allowed-origins: "http://localhost:4200"

spring:
  data:
    mongodb:
      host: "${MONGO_DB_HOST}"
      port: "${MONGO_DB_PORT}"
      database: "${MONGO_DB_NAME}"
      username: "${MONGO_DB_USERNAME}"
      password: "${MONGO_DB_PASSWORD}"

  profiles:
    active: "dev"