version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DATABASE}
      GENEMIS_DB_USERNAME: ${GENEMIS_DB_USERNAME}
      GENEMIS_DB_PASSWORD: ${GENEMIS_DB_PASSWORD}
    networks:
      - genemis-network
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - ./init-data:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    networks:
      - genemis-network
    depends_on:
      - mongo

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

networks:
  genemis-network:
    name: genemis-network
    driver: bridge