version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DATABASE}
      GENEMIS_USERNAME: ${GENEMIS_USERNAME}
      GENEMIS_PASSWORD: ${GENEMIS_PASSWORD}
    networks:
      - mongo-compose-network
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-adminpswd}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-adminpswd}@mongo:27017/
    networks:
      - mongo-compose-network

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

networks:
  mongo-compose-network:
    name: ${MONGO_NETWORK:-mongo.network}
    driver: bridge
