# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "architecture/**"
      - "backend/**"
      - "design/**"
      - "database/**"
      - "infrastructure/**"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "architecture/**"
      - "backend/**"
      - "design/**"
      - "database/**"
      - "infrastructure/**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: CI
      working-directory: /frontend/Genemis.Web
      run: npm ci
    - name: Build
      working-directory: /frontend/Genemis.Web
      run: npm run build --if-present
    - name: Test
      working-directory: /frontend/Genemis.Web
      run: npm test
